/**
 * Search types matching Rust backend structures
 */

export interface SearchRequest {
  query: string;
  intent?: SearchIntent;
  filters: SearchFilters;
  pagination: Pagination;
  enable_cloud: boolean;
  request_id: string;
  timestamp: string;
}

export type SearchIntent =
  | { type: 'FindFile'; file_type_hint?: FileType; time_hint?: TimeRange }
  | { type: 'FindContent'; content_type?: ChunkType; need_location: boolean }
  | { type: 'Ambiguous'; possible_intents: SearchIntent[]; clarification_questions: string[] };

export interface SearchFilters {
  file_types?: FileType[];
  tags?: string[];
  exclude_tags?: string[];
  time_range?: TimeRange;
  path_prefix?: string;
  min_score: number;
  exclude_private: boolean;
}

export interface TimeRange {
  start?: string;
  end?: string;
}

export interface Pagination {
  offset: number;
  limit: number;
}

export type FileType =
  | 'Document'
  | 'Image'
  | 'Video'
  | 'Audio'
  | 'Code'
  | 'Archive'
  | 'Model3D'
  | 'Other';

export type ChunkType =
  | 'Paragraph'
  | 'Heading'
  | 'CodeBlock'
  | 'Table'
  | 'Image'
  | 'Caption';

export interface SearchResponse {
  request_id: string;
  status: SearchStatus;
  results: SearchResult[];
  total_count: number;
  has_more: boolean;
  duration_ms: number;
  sources: ResultSource[];
  clarifications?: Clarification[];
}

export type SearchStatus =
  | 'Success'
  | 'PartialSuccess'
  | 'NeedsClarity'
  | 'NoResults'
  | 'Error';

export type ResultSource = 'LocalVector' | 'LocalTag' | 'CloudEnhanced';

export interface SearchResult {
  result_type: 'File' | 'ContentChunk';
  file: FileRecord;
  matched_chunk?: ContentChunk;
  score: number;
  preview: ResultPreview;
  highlights: Highlight[];
  tags: Tag[];
  source: ResultSource;
}

export interface FileRecord {
  id: string;
  path: string;
  filename: string;
  extension: string;
  file_type: FileType;
  size_bytes: number;
  content_hash: string;
  created_at: string;
  modified_at: string;
  indexed_at: string;
  last_accessed_at?: string;
  index_status: IndexStatus;
  privacy_level: PrivacyLevel;
  is_excluded: boolean;
}

export type IndexStatus = 'Pending' | 'Indexing' | 'Indexed' | 'Failed' | 'Skipped';
export type PrivacyLevel = 'Normal' | 'Sensitive' | 'Private';

export interface ContentChunk {
  id: string;
  file_id: string;
  chunk_index: number;
  chunk_type: ChunkType;
  content: string;
  location: ChunkLocation;
  vector_id: number;
  created_at: string;
}

export interface ChunkLocation {
  start_offset: number;
  end_offset: number;
  start_line?: number;
  end_line?: number;
  page_number?: number;
  bounding_box?: [number, number, number, number];
}

export interface ResultPreview {
  preview_type: 'Text' | 'Image' | 'Thumbnail' | 'Metadata';
  content: PreviewContent;
}

export type PreviewContent =
  | { type: 'Text'; snippet: string; full_text?: string }
  | { type: 'Image'; thumbnail_base64: string; width: number; height: number }
  | { type: 'Metadata'; entries: Record<string, string> };

export interface Highlight {
  start: number;
  end: number;
  highlight_type: 'ExactMatch' | 'SemanticMatch' | 'KeywordMatch';
}

export interface Clarification {
  question: string;
  options: ClarificationOption[];
}

export interface ClarificationOption {
  text: string;
  intent: SearchIntent;
  estimated_count?: number;
}

export interface Tag {
  id: string;
  name: string;
  display_name: Record<string, string>;
  parent_id?: string;
  tag_type: TagType;
  color: string;
  icon?: string;
  is_system: boolean;
  created_at: string;
  usage_count: number;
}

export type TagType =
  | 'Category'
  | 'FileType'
  | 'Project'
  | 'Status'
  | 'Custom'
  | 'AutoGenerated';
