/**
 * Tag types matching Rust backend structures
 */

export interface Tag {
  id: string;
  name: string;
  display_name: Record<string, string>;
  parent_id?: string;
  tag_type: TagType;
  color: string;
  icon?: string;
  is_system: boolean;
  created_at: string;
  usage_count: number;
}

export type TagType =
  | 'Category'
  | 'FileType'
  | 'Project'
  | 'Status'
  | 'Custom'
  | 'AutoGenerated';

export type TagSource = 'Manual' | 'AIGenerated' | 'Inherited' | 'Imported';

export interface FileTagRelation {
  id: string;
  file_id: string;
  tag_id: string;
  source: TagSource;
  confidence?: number;
  is_confirmed: boolean;
  is_rejected: boolean;
  created_at: string;
  user_action_at?: string;
}

export interface TagSuggestion {
  tag: Tag;
  confidence: number;
  reason: string;
}

export interface TagHierarchy {
  tag: Tag;
  children: TagHierarchy[];
  file_count: number;
}

export type TagCommand =
  | { type: 'ConfirmTag'; file_id: string; tag_id: string }
  | { type: 'RejectTag'; file_id: string; tag_id: string; block_similar: boolean }
  | { type: 'AddTag'; file_id: string; tag_id: string }
  | { type: 'RemoveTag'; file_id: string; tag_id: string }
  | { type: 'BatchTag'; file_ids: string[]; add_tags: string[]; remove_tags: string[] }
  | { type: 'CreateTag'; name: string; parent_id?: string; tag_type: TagType; color?: string }
  | { type: 'MergeTags'; source_tag_ids: string[]; target_tag_id: string };
